### ISSUE TITLE
`startBubble()` throws PlatformException(DASH_BUBBLE, lateinit property bubbleManager has not been initialized, null, null)

### ISSUE THREAD

**Issue by dunghce** [moazelsawaf/dash_bubble#7]
I get the following error, when `startBubble()` method is called while the app is on background:

```
[DashBubble] PlatformException: startBubble             
Please report this issue on GitHub via: https://github.com/moazelsawaf/dash_bubble/issues/new
E/flutter ( 7143): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(DASH_BUBBLE, lateinit property bubbleManager has not been initialized, null, null)
```

**Comment by moazelsawaf** [comment]
Hi @dunghce 👋🏻

I have tried to reproduce the error by calling `startBubble()` while the app is in the background, but the bubble starts correctly.

My reproduction approach was to add a button with a callback to start the bubble after a few seconds, which allowed me to move the app to the background.

Would you be able to share a minimal reproducible code? This would be very helpful for debugging and solving the error.

Thank you for your help 🙏🏻

**Comment by robilin** [comment]
Bubble  app crashes when the app is on background, this happens when  i start another app while bubble is in backgroud, app that i tried to start is call of duty game, I think it tried to prevend drawing on top of other apps, simila issue may be happening if there is another app that requires permission to run on top of other apps.

`  FATAL EXCEPTION: main
                                                                                                    Process: com.paisha.provider, PID: 32430
                                                                                                    java.lang.RuntimeException: Unable to create service dev.moaz.dash_bubble.src.BubbleService: com.torrydo.floatingbubbleview.PermissionDeniedException: "display over other app" permission IS NOT granted!
                                                                                                    	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4953)
                                                                                                    	at android.app.ActivityThread.access$1800(ActivityThread.java:310)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2300)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8663)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
                                                                                                    Caused by: com.torrydo.floatingbubbleview.PermissionDeniedException: "display over other app" permission IS NOT granted!
                                                                                                    	at com.torrydo.floatingbubbleview.FloatingBubbleService.onCreate(FloatingBubbleService.kt:56)
                                                                                                    	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4940)
                                                                                                    	at android.app.ActivityThread.access$1800(ActivityThread.java:310) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2300) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8663) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) `

**Comment by robilin** [comment]
I'am using foreground callback to help me bring back the app when clicked floating bubble icon

**Comment by moazelsawaf** [comment]
@robilin 

Thank you for bringing up the issue. However, it seems that the error messages and the problem you are facing are different from the original issue. Therefore, I suggest we handle this case in its separate issue #9 that you have created. This way, we can keep the discussion focused and ensure that each issue is resolved efficiently 🙏🏻

**Comment by moazelsawaf** [comment]
I’m sorry to hear that you’re facing difficulties with the issue 😞

Could you please provide more details about what you are trying to implement and the problem you’re experiencing. It would be better if you could provide minimal code and steps to reproduce the issue?

Additionally, please ensure that you have enabled the **Overlay Permission** through `hasOverlayPermission()` method before you start the bubble.

Lastly, could you clarify what do you mean by **while bubble is in background**? Because the bubble is either visible in both foreground and background or fully stopped in both cases, also please clarify when and how do you start the bubble.

**Comment by robilin** [comment]
Yes, thank you, I realised that after comment, that is why I had to 

> @robilin
> 
> Thank you for bringing up the issue. However, it seems that the error messages and the problem you are facing are different from the original issue. Therefore, I suggest we handle this case in its separate issue #9 that you have created. This way, we can keep the discussion focused and ensure that each issue is resolved efficiently 🙏🏻

Thank you, Yes, I realised that, that is why i created #9
